package main

var _headerTemplate = `
// Code generated by kratos tool genbts. DO NOT EDIT.

NEWLINE
/* 
  Package {{.PkgName}} is a generated cache proxy package.
  It is generated from:
  ARGS
*/
NEWLINE

package {{.PkgName}}

import (
	"context"
NEWLINE
	"github.com/CloudZou/punk/pkg/cache"
	{{.ImportPackage}}
)

{{if .UseBTS}}
var _ _bts
{{end }}
`
