package main

var _headerTemplate = `
// Code generated by punk tool genmc. DO NOT EDIT.

NEWLINE
/* 
  Package {{.PkgName}} is a generated redis cache package.
  It is generated from:
  ARGS
*/
NEWLINE

package {{.PkgName}}

import (
	"context"
	"fmt"
	{{if .UseStrConv}}"strconv"{{end}}
NEWLINE
	"github.com/CloudZou/punk/pkg/log"
	"encoding/json"
	{{.ImportPackage}}
)

var _ _redis
`
